In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib as mpl

print('pd ver = ', pd.__version__)
print('np ver = ', np.__version__)
print('sns ver = ', sns.__version__)
print('mpl ver = ', mpl.__version__)

pd ver =  1.2.4
np ver =  1.20.1
sns ver =  0.11.1
mpl ver =  3.3.4


In [4]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int32'

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
type(a)

numpy.ndarray

In [11]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[2:5]

array([2, 3, 4])

In [15]:
x[:-7]

array([0, 1, 2])

In [16]:
x[1:7:2]

array([1, 3, 5])

In [17]:
x[1:8:2]

array([1, 3, 5, 7])

In [18]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [19]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [20]:
y.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6])

In [21]:
y.min(axis=1)

array([ 0,  7, 14, 21, 28])

In [27]:
y.argmax(axis=0)

array([4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [28]:
np.where(y <10, y, 10*y)

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250, 260, 270],
       [280, 290, 300, 310, 320, 330, 340]])

In [33]:
np.argmin(y,axis=1)

array([0, 0, 0, 0, 0], dtype=int64)

In [34]:
np.argmax(y, axis=0)

array([4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [35]:
np.argmax(y,axis=1)

array([6, 6, 6, 6, 6], dtype=int64)

In [36]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
np.