In [1]:
import numpy as np
import pandas as pd

In [140]:
board = np.array([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]])
board = board.T

In [114]:
board
43113204

array([[0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 1, 5, 4, 1],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1]])

In [130]:
moves = np.array([1,5,3,5,1,2,1,4])
moves

array([1, 5, 3, 5, 1, 2, 1, 4])

In [131]:
extract = np.zeros(shape=(1,len(moves))).astype('int32')
extract

array([[0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
# 0이 있으면 통과하고 1이상의 숫자를 집어야함
# moves에서 값을 받아서 열 indexing 행은 0은 지나치고 나오는 1이상의 숫자 추출
# 추출한 값은 extract에 담고 같은 숫자가 생기면 pang_num +1

In [144]:
board = np.array([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]])
board = board.T
num = 0
pang_num=0
for i in moves:
    for j in range(5):
        if board[i-1][j] != 0:
            extract[0][num]=board[i-1][j]
            board[i-1][j]=0
            print('추출값=',extract[0][num])
            if (extract[0][num-1]==extract[0][num])&(num!=0):
                pang_num+=2
                num-=2
            num+=1
            print('num값=',num)
            break

def solution(board, moves):
    board = board.T
    num = 0
    pang_num=0
    for i in moves:
        for j in range(5):
            if board[i-1][j] != 0:
                extract[0][num]=board[i-1][j]
                board[i-1][j]=0
                if (extract[0][num-1]==extract[0][num])&(num!=0):
                    pang_num+=2
                    num-=2
                num+=1
                break
    answer = pang_num
    return answer





추출값= 4
num값= 1
추출값= 3
num값= 2
추출값= 1
num값= 3
추출값= 1
num값= 2
추출값= 3
num값= 1
추출값= 2
num값= 2
추출값= 4
num값= 3
[[4 2 4 1 2 4 4 0]]
4


In [150]:
import numpy as np
def solution(board, moves):
    extract = np.zeros(shape=(1,len(moves))).astype('int32')
    board = np.array(board)
    board = board.T
    num = 0
    pang_num=0
    for i in moves:
        for j in range(len(board)):
            if board[i-1][j] != 0:
                extract[0][num]=board[i-1][j]
                board[i-1][j]=0
                if (extract[0][num-1]==extract[0][num])&(num!=0):
                    pang_num+=2
                    num-=2
                num+=1
                break
    answer = pang_num
    return answer

print(solution([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]],[1,5,3,5,1,2,1,4]))

4
