In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print(np.array((4,4)))

[4 4]


In [7]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [10]:
def ppr(arr):
    print('type={}'.format(type(arr)))
    print('shape={},dim={},dtype={}'.format(arr.shape,arr.ndim,arr.dtype))
    print('arr data : \n',arr)

In [11]:
arr = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
ppr(arr)

type=<class 'numpy.ndarray'>
shape=(3, 4),dim=2,dtype=int32
arr data : 
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [12]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [13]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.arange(1,10).reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a1 = np.arange(1,10).reshape(3,3,-1)

In [20]:
ppr(a1)

type=<class 'numpy.ndarray'>
shape=(3, 3, 1),dim=3,dtype=int32
arr data : 
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [21]:
a3 = np.arange(1,49).reshape(2,2,3,4)

In [22]:
a3

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],

        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]]])

In [23]:
a3.astype(np.float64)

array([[[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]],


       [[[25., 26., 27., 28.],
         [29., 30., 31., 32.],
         [33., 34., 35., 36.]],

        [[37., 38., 39., 40.],
         [41., 42., 43., 44.],
         [45., 46., 47., 48.]]]])

In [24]:
arr1 = np.arange(1,5).reshape(2,2)

In [26]:
arr2 = np.arange(2,6).reshape(2,2)

In [27]:
arr1+arr2

array([[3, 5],
       [7, 9]])

In [28]:
arr1.dot(arr2)

array([[10, 13],
       [22, 29]])

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
idx = arr >3
print(idx)

[[False False False]
 [ True  True  True]]


In [33]:
a3.max()

48

In [34]:
a3.min()

1

In [37]:
arr.max(axis=1)

array([3, 6])

In [38]:
a3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [39]:
a3

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],

        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]]])

In [40]:
a3.ravel().max()

48